### ISSUE TITLE
Support for externalIPs in service yaml

### ISSUE THREAD

**Issue by PacketCrunch** [loxilb-io/kube-loxilb#17]
If a specific externalIP is provided in service definition,  kube-loxilb is unable to create service properly 

```
$ cat << EOF > nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  externalIPs:
    - 1.2.4.114
EOF
```

**Comment by TrekkieCoder** [comment]
With latest changes multiple externalIPs per service can be provided directly which does not rely on LB IPAM.

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb1
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: nginx-test
  ports:
    - port: 55002
      targetPort: 80
  type: LoadBalancer
  externalIPs:
    - 1.2.4.120
    - 1.2.4.121
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    what: nginx-test
spec:
  containers:
    - name: nginx-test
      image: nginx:stable
      ports:
        - containerPort: 80


```
