### ISSUE TITLE
Supports multi-port services using a single IP address

### ISSUE THREAD

**Issue by 6547709** [loxilb-io/kube-loxilb#172]
Issue Description:

I am using an external LoxiLB setup(kube-loxilb in kubernetes), and when creating a Service for Ingress-Nginx, regardless of the “setUniqueIP” configuration, LoxiLB assigns two IP addresses to the Service because it has two ports (80 and 443). Since Ingress access involves DNS resolution of domain names, it’s impractical to have two IP addresses, one for port 80 and another for port 443.

Temporary Solution:

I can temporarily solve this issue by specifying an IP address outside of IPAM using "loxilb.io/staticIP", which allows multi-port services to use a single IP address.

Suggestion:

Could you adjust the code so that for services with multiple ports, LoxiLB assigns only one IP address?

Desired results:
$ docker exec -it loxilb loxicmd get lb
|  EXT IP   | PORT  | PROTO |                  NAME                  | MARK | SEL  |  MODE   | # OF ENDPOINTS | MONITOR |
|-----------|-------|-------|----------------------------------------|------|------|---------|----------------|---------|
| 10.60.5.1 |    80 | tcp   | ingress-nginx_ingress-nginx-controller |    0 | hash | onearm  |              4 | On      |
| 10.60.5.1 |   443 | tcp   | ingress-nginx_ingress-nginx-controller |    0 | hash | onearm  |              4 | On      |

**Comment by TrekkieCoder** [comment]
Hi @6547709  Can you please provide kube-loxilb.yaml contents (the arguments) and also the service yaml ? It would help check the issue more. AFAIK, this should already be supported.

**Comment by 6547709** [comment]
@TrekkieCoder

**Comment by 6547709** [comment]
@TrekkieCoder 
Thank you for your reply, here are the relevant configurations.
Kube-LoxiLB.yaml
---
……
      containers:
      - name: kube-loxilb
        image: ghcr.io/loxilb-io/kube-loxilb:latest
        imagePullPolicy: Always
        command:
        - /bin/kube-loxilb
        args:
        - --loxiURL=http://10.40.45.8:11111,http://10.40.45.9:11111
        - --externalCIDR=10.60.4.0/24
        - --monitor
        - --setLBMode=2
        - --setUniqueIP=true
---
Ingress-Nginx-Service.yaml(Use Helm Install)
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    loxilb.io/epselect: hash
    loxilb.io/lbmode: onearm
    loxilb.io/liveness: "yes"
    loxilb.io/proberetries: "3"
    loxilb.io/probetimeout: "10"
    loxilb.io/staticIP: 10.60.5.1
    loxilb.io/usepodnetwork: "yes"
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.11.2
    helm.sh/chart: ingress-nginx-4.11.2
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  loadBalancerClass: loxilb.io/loxilb
  ports:
  - appProtocol: http
    name: http
    nodePort: 30988
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 30604
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
---
Ingress-Nginx-Helm-Install
---
helm upgrade --install ingress-nginx ingress-nginx \
  --repo https://kubernetes.github.io/ingress-nginx \
  --namespace ingress-nginx --create-namespace \
  --set controller.ingressClassResource.default=true \
  --set controller.service.type="LoadBalancer" \
  --set controller.service.loadBalancerClass="loxilb\.io/loxilb" \
  --set controller.service.annotations."loxilb\.io/lbmode"="onearm" \
  --set controller.service.annotations."loxilb\.io/epselect"="hash"  \
  --set controller.service.annotations."loxilb\.io/usepodnetwork"="yes" \
  --set controller.service.annotations."loxilb\.io/liveness"="yes" \
  --set controller.service.annotations."loxilb\.io/probetimeout"="10" \
  --set controller.service.annotations."loxilb\.io/proberetries"="3" \
  --set controller.kind=DaemonSet \
  --set controller.metrics.enabled=true \
  --set controller.allowSnippetAnnotations=true \
  --set-string controller.podAnnotations."prometheus\.io/scrape"="true" \
  --set-string controller.podAnnotations."prometheus\.io/port"="10254"  \
  --set controller.metrics.serviceMonitor.enabled=true \
  --set controller.metrics.serviceMonitor.additionalLabels.release="kube-prometheus-stack"
---
External LoxiLB Docker
---
docker run -u root --cap-add SYS_ADMIN --network=host \
  --restart always --privileged -dit \
  -v /dev/log:/dev/log \
  -v /etc/gobgp:/etc/gobgp \
  --name loxilb \
  ghcr.io/loxilb-io/loxilb:latest \
  --cluster=10.40.45.9 \
  --self=0 \
  --host=0.0.0.0 \
  --ka=10.40.45.9:10.40.45.8  \
  -b \
  -p
---

**Comment by 6547709** [comment]
@TrekkieCoder Thank you for your reply, here are the relevant configurations.
Kube-LoxiLB Args
```
      containers:
      - name: kube-loxilb
        image: ghcr.io/loxilb-io/kube-loxilb:latest
        imagePullPolicy: Always
        command:
        - /bin/kube-loxilb
        args:
        - --loxiURL=http://10.40.45.8:11111,http://10.40.45.9:11111
        - --externalCIDR=10.60.4.0/24
        - --monitor
        - --setLBMode=2
        - --setUniqueIP=true
```
Ingress-Nginx Service (Use Helm Install)
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    loxilb.io/epselect: hash
    loxilb.io/lbmode: onearm
    loxilb.io/liveness: "yes"
    loxilb.io/proberetries: "3"
    loxilb.io/probetimeout: "10"
    loxilb.io/staticIP: 10.60.5.1
    loxilb.io/usepodnetwork: "yes"
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.11.2
    helm.sh/chart: ingress-nginx-4.11.2
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  loadBalancerClass: loxilb.io/loxilb
  ports:
  - appProtocol: http
    name: http
    nodePort: 30988
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 30604
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
```
External LoxiLB Docker(Use GARP for VIP)
```
docker run -u root --cap-add SYS_ADMIN --network=host \
  --restart always --privileged -dit \
  -v /dev/log:/dev/log \
  -v /etc/gobgp:/etc/gobgp \
  --name loxilb \
  ghcr.io/loxilb-io/loxilb:latest \
  --cluster=10.40.45.9 \
  --self=0 \
  --host=0.0.0.0 \
  --ka=10.40.45.9:10.40.45.8  \
  -b \
  -p
```
