### ISSUE TITLE
no active endpoints returns when create a ipv6 loxilb in Local externalTrafficPolicy

### ISSUE THREAD

**Issue by celiawa** [loxilb-io/kube-loxilb#212]
**Problem description:**
We setup up the external mode loxilb. Version: v0.9.7
When we create a service with below manifest. The externalIP always stuck in pending. 
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb1-ipv6
  annotations:
   # If there is a need to do liveness check from loxilb
   loxilb.io/liveness: "no"
   # Specify LB mode - one of default, onearm or fullnat
   loxilb.io/lbmode: "default"
   # Specify loxilb IPAM mode - one of ipv4, ipv6 or ipv6to4
   loxilb.io/ipam: "ipv6"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: nginx-test-ipv6
  ports:
    - port: 55002
      targetPort: 80
  type: LoadBalancer
  ipFamilies:
    - IPv6
````

kube-loxi log:
```
E1206 13:45:22.926339       1 loadbalancer.go:663] getEndpoints return error. err: no active endpoints
E1206 13:45:22.926472       1 loadbalancer.go:348] Error syncing LoadBalancer {default nginx-lb1-ipv6}, requeuing. Error: no active endpoints
```

In this [code line](https://github.com/loxilb-io/kube-loxilb/blob/0a5f34bd2f20eff2ee0b3a8edca9ae5cfc486078/pkg/k8s/node.go#L80), it trys to get the node ipv6 address from pod.status.hostip. But pod.status.hostIP generally returns the IPv4 address of the node where the pod is running, even in a dual-stack or IPv6 environment. 

Our environment is dual-stack, the pod.status.hostip is ipv4 address.
 
Could you please take a look. Thanks.
