### ISSUE TITLE
Support for end-point liveness on a per service basis

### ISSUE THREAD

**Issue by loxi-admin** [loxilb-io/kube-loxilb#4]
Currently, liveness health check is based on global monitor flag of kube-loxilb. It should be better to have it on per-service basis.

**Comment by TrekkieCoder** [comment]
The following liveness annotation will enable active liveness check for Lb services via loxilb    
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb1
  annotations:
   loxilb.io/liveness : "yes"
spec:
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: nginx-test
  ports:
    - port: 55002
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    what: nginx-test
spec:
  containers:
    - name: nginx-test
      image: nginx:stable
      ports:
        - containerPort: 80
 ```
